# NumPy exercises

We are going to practice NumPy skills and basic syntax.

We put here also some examples that were not in the tutorial on purpose. Try to use google and offial NumPy documentation to solve these exercises.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Create a null vector of size 10 (★☆☆)

In [2]:
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 3.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [3]:
b= np.zeros(10)
b[4] =1
b

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 4.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [6]:
c = np.arange(10,50)
c

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 5.  Reverse a vector (first element becomes last) (★☆☆)

In [33]:
a = np.array([1,2,3,4,5])
np.flip(a)


array([5, 4, 3, 2, 1])

#### 6.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [16]:
np.random.randint(0,9,size = (3,3))

array([[4, 5, 3],
       [7, 1, 8],
       [6, 4, 8]])

#### 7. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [32]:
a=[1,2,0,0,4,0]
np.nonzero(a)

(array([0, 1, 4]),)

#### 8. Create a 3x3x3 array with random values (★☆☆)

In [23]:
b = np.random.randn(3,3,3)
b

array([[[ 0.54159253,  0.65382753,  1.15842586],
        [ 0.30074372,  0.42220493,  1.06896785],
        [-1.09375257,  0.73951825, -0.28732904]],

       [[-0.53452207,  0.51590944, -0.78196941],
        [-0.38763728,  0.247171  , -1.96059503],
        [ 0.36886158, -0.02042402,  1.52777426]],

       [[ 0.01480022, -1.08987401,  1.19010667],
        [-0.13535527,  0.58743325, -0.54593105],
        [-2.3196027 ,  1.06664721, -0.06700982]]])

#### 9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [38]:
arr=np.random.randn(10,10)
a = arr.max()
b=arr.min()

#### 10. Create a random vector of size 30 and find the mean value (★☆☆)

In [42]:
np.random.rand(30).mean()

0.5149622485320954

#### 11. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [53]:
a= np.ones((3,3))
a[1,1]=0
a

array([[1., 1., 1.],
       [1., 0., 1.],
       [1., 1., 1.]])

#### 12. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [58]:
np.pad(a, pad_width=1, constant_values =0)



array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 0., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

#### 13. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
nan
False
False
nan
True
False

#### 14. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [62]:
np.diag([1,2,3,4], k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 15. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [66]:
a=np.arange(336).reshape(6,7,8)
np.unravel_index(100, (6,7,8))

(1, 5, 4)

#### 16. Normalize a 5x5 random matrix (★☆☆)

In [73]:
a=np.random.rand(5,5)
norm = np.linalg.norm(a)
result = a/norm

result

array([[0.24007438, 0.293963  , 0.12461759, 0.10454458, 0.28863907],
       [0.07763307, 0.14032554, 0.31897701, 0.18145364, 0.22393884],
       [0.09637341, 0.28045772, 0.3272314 , 0.16497022, 0.216872  ],
       [0.01257909, 0.11744585, 0.0631297 , 0.32826722, 0.0357073 ],
       [0.13656352, 0.18171778, 0.22787301, 0.1821684 , 0.05111397]])

#### 17. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [82]:
a=np.random.randint(10,size=5)
a[(a>=3) & (a<=8)] *=-1
a

array([-4,  9, -3, -5,  2])

#### 18. How to round away from zero a float array ? (★☆☆)

In [89]:
a=np.random.random(10)
print(a)
np.round(a,0)

[0.86242775 0.2532379  0.29576423 0.77482575 0.21392534 0.00640277
 0.22001924 0.10294582 0.27805043 0.97434904]


array([1., 0., 0., 1., 0., 0., 0., 0., 0., 1.])

#### 19. Find common values between two arrays? (★☆☆)

In [91]:
a=np.array([1,2,3,4,5])
b=np.array([3,4,7,8,9])
np.intersect1d(a,b)

array([3, 4])

#### 20. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
false

#### 21. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [ ]:
def generator():
    for i in range(10):
        

#### 22. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [121]:
a=np.random.rand(10)
a

array([0.50686844, 0.33304506, 0.97871175, 0.27298384, 0.98100963,
       0.01880904, 0.19006121, 0.51284895, 0.6333458 , 0.20770217])

#### 23. Create a random vector of size 10 and sort it (★★☆)

In [123]:
a=np.random.rand(10)
a.sort()
a

array([0.05788476, 0.16842326, 0.1733258 , 0.248688  , 0.24974517,
       0.28603121, 0.64710918, 0.64911662, 0.70387698, 0.78271162])

#### 24. Consider two random arrays A and B, check if they are equal (★★☆)

In [136]:
A = np.random.randint(10,20,5)
B = np.random.randint(10,20,5)

np.array_equal(A,B)

False

#### 25. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [135]:
a=np.random.rand(10)
a[a.argmax()] =0
a


array([0.86565399, 0.53504096, 0.41947809, 0.82071867, 0.06011832,
       0.9216097 , 0.27178439, 0.49855598, 0.        , 0.874791  ])

#### 26. Find the closest value to random element in a vector? (★★☆)

In [169]:
a=np.random.rand(10)
print(a)
b=0.5
arr=np.abs(a-b)
index=arr.argmin()
index
result = a[index]
print(result)

[0.21209529 0.88347981 0.92608915 0.55669208 0.29869133 0.2179132
 0.97297136 0.39827266 0.11514901 0.25935429]
0.5566920760100932


#### 27. Convert a float (32 bits) array into an integer (32 bits) in place?

In [150]:
a=np.random.rand(4).astype(np.float32)*10
a
a.astype(int)

array([5, 9, 0, 7])

#### 28. Sort an array by the nth column? (★★☆)

In [177]:
arr=np.random.randint(20,size=(4,3))
#sort by nth column and swap rows 
print(arr)

def sort_by_column(arr,col):
    return arr[arr[:,col].argsort()]
sort_by_column(a,1)

np.argsort()

[[18 13 10]
 [ 7  5 18]
 [12  9 13]
 [ 1 18  4]]
[13  5  9 18]
[1 2 0 3]
[[ 7  5 18]
 [12  9 13]
 [18 13 10]
 [ 1 18  4]]


#### 29. Find if a given 2D array has null (empty) columns? (★★☆)

In [204]:
a=np.random.randint(0,2,size=(10,10))
print(a)
(~a.any(axis=0)).any()

[[1 1 1 1 1 0 1 1 1 0]
 [1 0 0 1 0 1 1 1 0 0]
 [0 0 1 0 0 0 0 0 1 1]
 [1 1 0 0 1 1 1 1 0 1]
 [1 0 0 0 1 0 0 1 0 0]
 [0 0 0 1 1 1 1 0 0 0]
 [0 0 0 0 1 1 1 0 1 1]
 [0 1 0 1 1 0 0 1 0 1]
 [0 0 0 0 0 0 1 0 0 0]
 [0 1 0 0 0 0 1 1 0 0]]


False

#### 30. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [221]:
a = np.array([1,2,3,4,5])
size_zero = (len(a)-1)*3+len(a)
new = np.zeros(size_zero)
new[::4] =a
new

array([1., 0., 0., 0., 2., 0., 0., 0., 3., 0., 0., 0., 4., 0., 0., 0., 5.])

#### 31. Swap two rows of an array? (★★★)

In [241]:
a=np.arange(15).reshape(3,5)
print(a)
a[[0,2]] = a[[2,0]]
a

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


array([[10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4]])

#### 32. How to negate a boolean value inside an array? (★★★)

In [247]:
a=np.random.randn(10)
print(a)
print(np.negative(a))

[-0.4466356   0.6342963   2.35052443 -1.09267811 -1.4802948   0.65304652
  0.73373542 -1.34674577  0.28578972 -0.04621365]
[ 0.4466356  -0.6342963  -2.35052443  1.09267811  1.4802948  -0.65304652
 -0.73373542  1.34674577 -0.28578972  0.04621365]


#### 33. Find the most frequent value in an array?

In [265]:
a=np.random.randint(0,10,size=6)
print(a)
count=np.bincount(a)
count
count.argmax()

[7 9 5 5 3 9]


5

#### 34. Get the n largest values of an array (★★★)

In [301]:
arr=np.random.randint(0,10,size=6)
print(arr)

index = np.argsort(arr)
  
# sorted array
sorted_arr = arr[index]  
# we want 3 largest value
n = 3

rslt = sorted_arr[-n : ]
rslt

[8 6 5 9 0 3]


array([6, 8, 9])

#### 35. Extract unique rows from a two dimensional array? (★★★)

In [311]:
arr = np.zeros((3,3))
arr[1,1]=9
arr

np.unique(arr,axis=0)

array([[0., 0., 0.],
       [0., 9., 0.]])